language: python
python:
  - "3.6"
install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  - "pip install -e ."
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - nosetests --with-coverage --cover-package=dlhub_toolbox
  - cd examples
  - ./run_examples.sh
after_success:
  coveralls
