language: python
python:
- '3.6'
cache: pip
jobs:
  include:
  - name: Latest libraries
  - name: Keras 2.1.3
    env: KERAS_VERSION=2.1.3
  - name: Keras 2.2.3
    env: KERAS_VERSION=2.2.3
  - name: Older Scikit-Learn
    env: SKLEARN_VERSION=0.19.1
before_install:
# Decrypt the tokens
- openssl aes-256-cbc -K $encrypted_8839f1a6488f_key -iv $encrypted_8839f1a6488f_iv
  -in test-files/funcx_sdk_tokens.json.enc -out test-files/funcx_sdk_tokens.json -d
- openssl aes-256-cbc -K $encrypted_548e88740293_key -iv $encrypted_548e88740293_iv
  -in test-files/tokens.cfg.enc -out test-files/tokens.cfg -d

# Move to proper locations
- cp test-files/tokens.cfg ~/.globus-native-apps.cfg
- mkdir -p ~/.funcx/credentials
- cp test-files/funcx_sdk_tokens.json ~/.funcx/credentials/funcx_sdk_tokens.json
install:
- source ./travis/install.sh
- pip list
script:
- flake8 .
- travis_wait 50 pytest --cov=dlhub_sdk
deploy:
  provider: pypi
  user: wardlt
  skip_existing: true
  distributions: sdist bdist_wheel
  password:
    secure: YUgONy8UjgchN4lCOMjsw4StF9Iq3PzZbeZqJP4/xhlRDIyLPViNSBFxfBiyjiKDzemceVzQyQpvsoe2Xq1mqoLBXXlTGnJL6nh6BXs1MRRY1CCYJmQpzetdhmtPnq6xp51R0FbYbv1Iifv/kL0NiHXh/Hw9HPjamzSO4X+4b01tyvt+cXNjGgGM06E73h8LMANIPecjUqdeLxDL//V1wB3An87Eu+YIVDoUzeApx/2GVIf7mH5tOnGjV4+5GhOUePsEQArVw7B4KngQ+B28Be07/GUTWd39DOmWJrZUKKQBrUpwjsusz0N5gQTxnhoPzIICaT2vnQoUruZMGN4or050gDW0apnvmpb/LQFkwmBj71XvX0hqN4NGLsN5pHW3lQAncMC61o1Ybm9I/RTzpnjTerdskMGBUwod3TVQz3m+H2LsvNPZsGyHVE/IZ700BQLw+qCjGXN8UcnmLcSsXjVuWpFgeB5YTtAwuueFz13A/0h4+Nwn1JUbg5x55ahs+KWXSfBybETuzxWpY2k/sq0ZOVT9FQbLONJdwO2PlRNAR25wMAFOH9/uTisJWxvmAItmlgGotXiZsu/tZGUDA5FgaU0XXs3QJivGcV4CrPyl+Wvx0ZZ25njq5d5JETi/vJHKgNsxcsQHVQiZRmak/oWEUW1jXDDTraVcxQ3mbPw=
  on:
    tags: true
    branch: master
after_success: coveralls
