language: python
python:
  - "3.6"
install: 
    - "pip install -e ."
    - pip install coveralls
    - cd examples
    - ./run-examples
script: nosetests --with-coverage --cover-package=dlhub_toolbox
after_success:
  coveralls
