language: python
python:
  - "3.6"
install:
  - pip install --upgrade pip setuptools wheel
  - "pip install -e ."
  - pip install coveralls
  - pip install --only-binary=numpy,scipy -r requirements.txt
  - pip install -r requirements.txt
script:
  - nosetests --with-coverage --cover-package=dlhub_toolbox
  - cd examples
  - ./run_examples.sh
  - cd .. # So that coveralls works
after_success:
  coveralls
