# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: daily-testing

on:
  push:
    branches:
      - gha-testing
  schedule:
    # daily testing to occur at 7:30 CST every day
    - cron:  '30 13 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
        keras-version: [2.1.3, 2.2.3]

    env:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Globus auth
      run: 'echo "$GLOBUS_CONFIG" > ~/.globus-native-apps.cfg'
      shell: bash
      env:
        GLOBUS_CONFIG: "${{ secrets.GLOBUS_CONFIG }}"

    - name: Run Installation Script
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install mdf-connect-client
        pip install flake8 pytest
        pip install -r test-requirements.txt
        pip install keras==${{matrix.keras-version}}
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        # run all testing documents, except the local tests
        pytest -s ./dlhub_sdk -k 'not test_dlhub_client'
